apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: production-eck
spec:
  version: 7.13.2
  count: 2
  http:
    service:
      spec:
        type: ClusterIP # default is ClusterIP
  
  elasticsearchRef:
    name: "production-eck"
    serviceName: production-eck-es-coordinating 
  #   namespace: default
  config:
    elasticsearch.ssl.verificationMode: certificate
  podTemplate:
    spec:
      containers:
      - name: kibana
        # image: docker.elastic.co/kibana/kibana:7.13.2
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 2
      # nodeSelector:
      #   type: frontend
